wslyvh/useWeb3

src/assets/styles/globals.scss
src/components/layouts/main.module.scss

Fixing https://github.com/wslyvh/useWeb3/issues/1

Fix double scroll issue

---

src/components/sitenav.module.scss
src/components/sitenav.tsx

currently user cannot see the active tab visually this PR fix this.

feat: make current tab active

---

content/courses/hyperledger-university-course.md

Adds a free open source course focused on Hyperledger technologies 
https://github.com/hyperledger-labs/university-course

course: add hyperledger university course

---

content/starter-kits/chainlink-mix.md
content/starter-kits/dapptools-starter-kit.md
content/starter-kits/hardhat-starter-kit.md
content/tutorials/how-to-use-dapptools.md
content/videos/become-a-defi-quant.md
content/videos/how-to-make-nft-art-with-on-chain-metadata.md
content/videos/learn-dapptools.md
content/videos/logging-events.md
content/videos/nft-erc-721-collectible-end-to-end-tutorial.md

Hey hey!
Let me know if these work :)

added a ton of updates from patrick collins

---

content/courses/encodeclub-bootcamps.md

Encode Club is one of the biggest web3 education communities working alongside the leading protocols in crypto in order to deliver fantastic events such as education series, coding bootcamps, hackathons and accelerators. We then help people get a job or secure funding for the projects they are building.

Add encodeclub-bootcamps.md

---

content/podcasts/Web3 with Sam Kamani

New Podcast, a top 200 technology podcast. 
More information:- https://anchor.fm/web3podcast
or https://web3pod.xyz/

Create Web3 with Sam Kamani Podcast

---

content/courses/learnweb3.md

https://learnweb3.io
https://twitter.com/LearnWeb3DAO

Add LearnWeb3 DAO to Courses

---

content/courses/learn-blockchain-solidity-full-stack-web3-javascript.md
content/tutorials/full-stack-web3-everything-you-need-to-know.md
content/tutorials/learn-to-build-an-on-chain-dao.md
content/videos/how-to-connect-smart-contracts-to-metamask-full-stack-web3.md
content/videos/learn-blockchain-solidity-full-stack-web3-javascript.md
content/videos/learn-foundry.md
content/videos/learn-to-build-an-on-chain-dao.md

Let me know what you think @wslyvh !

added patricks 32 hour js megacourse, and a few others

---

content/podcasts/dev3.md

Already tested locally. I *believe* everything is formatted properly

✨ Add dev3 podcast

---

content/starter-kits/web3-starter-kit.md

A quick starter to build on Ethereum and Polygon! 💜

Add web3-starter-kit.md 

---

content/guides/Ethereum-Smart-Contract-Auditor-Roadmap.md

A Smart Contract Auditor Roadmap, designed as a step-by-step approach for beginners to follow.

Ethereum-Smart-Contract-Auditor-Roadmap

---

content/starter-kits/ethathon.md

Hey @wslyvh :) I just added the new boilerplate I'm maintaining for a few weeks now. I think it's ready for others to be used ⚡

Add starter-kit: ETHathon

---

content/tutorials/zk-snarks-with-circom.md

The circom language is a very useful resource for implementing zero knowledge proofs in your smart contracts, and it is also a great starting point for curious developers. Both Dark Forest and Cyclone Currency (mixing service that should not be named) were built using circom.

add circom as zk-snark resource

---

content/courses/metaschool.md

added new course platform 

---

content/courses/developing-applications-on-ethereum-blockchain.md

Updated a link to point to the new version of the "Developing Applications on Ethereum Blockchain" course.

Updated a link for the "Developing Applications on Ethereum Blockchain" course

---

content/books/lexon-digital-contracts.md
content/guides/Ethereum-Smart-Contract-Auditor-Roadmap.md
content/movies/hopium-diaries.md
content/podcasts/epicenter.md
content/tutorials/get-to-know-ethereum-calldata.md
content/videos/become-a-defi-quant.md
content/videos/dune-analytics-tutorial-series.md
content/videos/send-eth-payments.md
content/videos/transfer-any-erc20-token-from-your-smart-contract.md
content/websites/cairo-by-example.md
src/pages/index.tsx

Fix: typos

---

content/books/Solidity-Design-Patterns.md

Solidity design patterns book provides a detailed explanation of popular design patterns like the Security, Gas Optimisation, Proxy, and many more. It also covers the latest design patterns used in the development of decentralized finance (DeFi) applications. The ebook provides a step-by-step guide to help developers understand and implement these patterns to create high-quality smart contracts.

Solidity-Design-Patterns Books

---

content/starter-kits/create-web3-dapp.md

added [create-web3-dapp](https://createweb3dapp.alchemy.com/) to starter kits.

add create-web3-dapp to starter kits

---

content/tutorials/smart-contract-audit-explainer.md

I added a tutorial on what a smart contract audit is, what to expect, and what to not expect. Let me know what you think!

🤓 Smart Contract Audit explainer!

---

content/tutorials/fuzzing-and-invariant-test-introduction.md
content/videos/fuzz-and-invariant-testing.md

Added content around fuzz testing!

fuzzzzzzzzzzzz

---

.github/PULL_REQUEST_TEMPLATE.md

I have created a professional GitHub PR template that includes all the information and guidelines you provided

PR-template added

---

content/tutorials/formal-verification-and-symbolic-execution.md

title: "Formal Verification & Symbolic Execution | The Security Silver Bullet?"
description: "We look at formal verification & symbolic execution with two Trail of Bits Web3 security team members. Additionally, we review the value these techniques bring and compare them to other tools."
authors: ["@patrickalphac"]
tags: ["Smart Contracts", "Security"]
languages: ["Solidity"]
url: "https://patrickalphac.medium.com/formal-verification-symbolic-execution-the-security-silver-bullet-38e0ac9072eb"
dateAdded: 2023-04-25
level: "intermediate"
date: 2023-04-25
Thank you for your contribution!

added formal verification and symbolic execution

---

content/starter-kits/sveltekit-evm-bootstrap

Adds sveltekit-evm-boostrap starter kit

Add sveltekit-evm-bootstrap starter kit

---

content/tutorials/Build-your-own-Decentralized-Exchange.md
content/tutorials/Building-a-Voting-Smart-Contract.md

Adding Tutorials to Building your own Decentralized Exchange and Voting Smart Contract

---

content/tutorials/Building-an-NFT-Lottery-Step-by-Step-Guide-for-Creating-a-Smart-Contract-and-Frontend.md
content/tutorials/Mastering-Smart-Contract-Testing-A-Comprehensive-Guide-to-Hardhat.md

Adding  Tutorial on building NFT lottery and Hardhat framework

---

content/code-challenges/wriggly.md

[Wriggly] Adding Wriggly to Code Challenges

---

content/websites/bestinweb3.md

Adding BestInWeb3 to websites

---

content/tutorials/Build-Your-Own-Decentralized-Lending-Protocol.md
content/tutorials/Euler-Finance-196-Million-Flash-Loan-Exploit.md
content/tutorials/Learn-and-deploy-an-ERC-1155-smart-contract.md
content/tutorials/Recreating-Kubz-NFT-Hack.md

added tutorial related to ERC115, flash loan hacks

---

content/code-challenges/dappworld.md

added dappworld in codechallenges

---

content/tutorials/Creating_Royalty_NFTs_using_ERC2981.md
content/tutorials/Deploy_Your_Own_Azuki_ERC721A_NFT_with_BuildBears_NoCode_Deployment.md
content/tutorials/Deploy_Your_Own_ERC721_NFT_Staking_with_Infinite_Rewards_with_BuildBears_NoCode_Deployment
content/tutorials/Learn_How_to_Create_Liquidity_Pools_on_UniswapV3_for_New_ERC20_Tokens.md
content/tutorials/Learn_How_to_Perform_a_Sandwich_Attack.md
content/tutorials/NoCode_Smart_Contract_Development_and_Deployment_to_Your_Private_Testnet_with_Just_1_Click.md
content/websites/List-of-Faucets-for-Public-Testnets.md

added Tutorial and faucet curation website. 

---

content/grants/Bepro Infrastructure Grant

Hi! I'd like to submit the new Bepro Infrastructure Grant for builders or projects that want to accelerate their development using our infrastructure.
Please, if I should make any changes, let me know and I'll be happy to do it. Thanks!
- Please check and …

Create Bepro Infrastructure Grant

---

content/grants/zetachain.md

Added ZetaChain Grants

---

content/tutorials/Deploy-Your-Own-Royalty-Splitter-Contract-with-BuildBear’s-No-Code-Deployment.md
content/tutorials/Enhance-Your-Web3-Development-with-These-Essential-Tools.md
content/tutorials/In-Depth-Technical-QA-Dive-into-UniLendV2-Reporting-a-Front-End-Bug.md
content/tutorials/Most-Common-Vulnerabilities-In-Solidity-In-Depth-Part-1.md
content/tutorials/Most-Common-Vulnerabilities-In-Solidity-In-Depth-Part-2.md
content/tutorials/Understanding-the-Mechanics-of-Aave-V3.md

added Tutorial articles 

---

content/tutorials/Meet-Holesky-Ethereums-Latest-Testnet.md
content/tutorials/Must-Have-Smart-Contract-Auditing-Tools.md
content/tutorials/QA-testing-dyson.md

added Tutorial articles. 

---

content/earn/overmind.md

My company, Overmind, would like to be featured on your site. We do weekly quests on Smart contract or dApp development.

Add Overmind to Earn category of website

---

content/tutorials/3A-DAO-Chosen-BuildBear-Sandbox-for-Beta-Testing-their-Lending-Protocol.md
content/tutorials/Elevate-Protocol-Development-Testing-with-Catapulta-and-BuildBear-Sandbox-Integration.md
content/tutorials/In-Depth-Guide-on-ERC-4626-Tokenized-Vaults.md
content/tutorials/Optimize_Your_Dapp_Development_and_Testing_with_Hardhat_BuildBear.md
content/tutorials/Simplify-and-Optimize-Protocol-Deployments-with-Catapulta.md

Add Tutorial articles 

---

content/tutorials/Automate-Contract-Deployment-with-Hardhat-Ignition.md
content/tutorials/Learn-How-to-integrate-UniswapV3-into-your-smart-contracts.md

added tutorials. 

---

content/videos/bridge-token-on-chain.md

add bridge token on-chain video

---

content/videos/how-to-send-messages-cross-chain-with-axelar.md

feat: add how to send messages cross-chain with axelar video

---

content/tutorials/how-to-build-a-cross-chain-airdrop-dapp.md

feat: add cross-chain airdrop dapp

---

content/tutorials/how-to-deploy-a smart-contract-at-the-same-address-on-different-blockchains.md

feat: add same address deployer tutorial

---

content/tutorials/how-to-build-interchain-dapp-with-next.js-solidity-and-axelar.md

feat: add fullstack interchain dapp tutorial

---

content/tutorials/create-a-2-way-cross-chain-communication-smart-contract-solidity.md

feat: add 2 way communication smart contract tutorial

---

content/starter-kits/turboeth.md

Adding [turboeth](https://www.turboeth.xyz/) as a web3 template.
- Please check and use existing tags from the site https://www.useweb3.xyz/tags - Do not use any other tags. If you feel like something is missing, please create a separate …

adding turboeth as a template

---

content/books/foundations-of-distributed-consensus.md
content/books/read-write-own.md
content/books/web3-chartering-the-next-frontier.md
content/books/web3-the-insights-harvard-business-review.md
content/courses/alchemy-university.md
content/courses/bankless-academy.md
content/courses/bitcoin-and-cryptocurrency.md
content/courses/cryptolectures.md
content/courses/dapp-world.md
content/courses/de-university-of-ethereum.md
content/courses/distributed-systems-course.md
content/courses/human-dao-academy.md
content/courses/macro.md
content/courses/mastering-blockchain-and-dlt.md
content/courses/nfts-and-metaverse.md
content/courses/proto-school.md
content/courses/third-academy.md
content/movies/ruin-ftx-documentary.md
content/movies/the-blockchain-life.md
content/tutorials/awesome-web3.md
content/tutorials/blockchain-development-resources.md
content/tutorials/ethereum-developer-tools-list.md
content/tutorials/snakecharmers.md
content/websites/cryptopedia.md
content/websites/free-web3-resources.md
content/websites/solidity-tips.md
content/websites/web3-creators.md

Gm, I suggested some resources. Feel free to correct / edit them. 
Love to see how the project evolved 👍

Add a couple resources

---

content/guides/Guide-on-Crypto-applications-Product-Market-Fit.md
content/guides/How-to-Protect-Your-Crypto-Wallet-95-percent-of-the-Time.md
content/guides/ways-to-reduce-Gas-Fee-paid-to-Ethereum-blockchain.md
content/tutorials/Enhance-Your-Smart-Contract-Development-with-the-Integration-of-LokiCode-and-BuildBear-Sandbox.md
content/tutorials/Guide-to-Becoming-a-Web3-Developer-in-2024.md
content/tutorials/Inscription-Spam-Disrupting-Developer-Experiences-on-Public-Testnets.md
content/tutorials/Introducing-Scaffold-ETH-2-with-the-power-of-Mainnet-Forks.md

new tutorials and guides added.

---

content/tutorials/Implementing-NFT-RoyaltiesA-Practical-Tutorial-on-ERC721-C.md
content/tutorials/Learn-how-Stablecoins-work-and-Create-Your-own-Version-Similar-to-USDC.md
content/tutorials/What-Is-the-Ethereum-Cancun-Deneb-Update.md

Added Tutorials 

---

.github/workflows/links.yml

Add link checker (https://github.com/wslyvh/useWeb3/issues/115)

Add link checker

---

content/guides/intro-to-defi.md

Adding a guide about DeFi, #32
Feeld free to adapt it or let met know what to change. I tried to include some developer resources but there's probably much more (-:

Add a DeFi guide

---

content/tutorials/A _Deep_Dive _into _ERC-404_and _Crafting your_Custom_Token.md
content/tutorials/A_Comprehensive_Guide_to_ERC-6672-Multi-Redeemable_NFTs.md
content/tutorials/A_Practical_Guide_on_Honeypot_Attacks_in_Smart_Contracts.md
content/tutorials/Understanding_Decentralized_Identity_with_Smart_Contract.md

Added new articles

---

content/books/zk-proofs-eli5.md

- Adding ZK Proofs ELI5, online book on https://eli5.zksync.io/
- Please check and use existing tags from the site https://www.useweb3.xyz/tags - Do not use any other tags. If you feel like something is missing, please create a separate …

Adds ZK Proofs: ELI5

---

src/services/issue.ts

add cryptography orgs to open source issue finder

---

content/starter-kits/dappBoilerplate.md
src/pages/support.tsx

chore: fix some comments

---

content/websites/kiwi-news.md

Kiwi update

---

content/guides/what-is-web3.md
content/podcasts/protocol-explorer.md
content/starter-kits/mev-template.md
content/tutorials/build-your-own-decentralized-lending-protocol.md
content/tutorials/solidity-gas-optimizations-series.md
content/tutorials/starknet-cairo-101.md

chore: fix some typos in comments

---

content/courses/deschool.md
content/courses/learn-crypto.md
content/earn/metagame.md
content/movies/ethereum-the-infinite-garden.md
content/websites/eip-fun.md
content/websites/growthepie.md

Suggested some resources, happy to adapt anything if needed.

add resources

---

content/websites/2077-research.md

chore(feat): add 2077 research resource

---

src/assets/styles/themes/dark.scss
src/assets/styles/themes/light.scss

chore: fix some typos in comment

---

content/starter-kits/dappbooster
content/starter-kits/dappbooster.md

Add dAppBooster to web3 starter kits list

---

content/websites/growthepie.md

Updated title, description, and URL for growthepie.
- …

Revise growthepie metadata and description
